-- Inserção de cursos
INSERT INTO Curso (Nome) VALUES
('Desenvolvimento de Software Multiplataforma'),
('Meio Ambiente e Recursos Hídricos'),
('Geoprocessamento');

-- Inserção de turmas
INSERT INTO Turma (Nome, Curso_idCurso, Turno) VALUES
('1 DSM', '1', 'Noturno'),
('2 DSM', '1', 'Noturno'),
('3 DSM', '1', 'Noturno'),
('4 DSM', '1', 'Noturno'),
('5 DSM', '1', 'Noturno'),
('6 DSM', '1', 'Noturno'),
('1 MARH', '2', 'Noturno'),
('2 MARH', '2', 'Noturno'),
('3 MARH', '2', 'Noturno'),
('4 MARH', '2', 'Noturno'),
('5 MARH', '2', 'Matutino'),
('6 MARH', '2', 'Matutino'),
('1 GEO', '3', 'Noturno'),
('2 GEO', '3', 'Noturno'),
('3 GEO', '3', 'Noturno'),
('4 GEO', '3', 'Noturno'),
('5 GEO', '3', 'Noturno'),
('6 GEO', '3', 'Noturno');

-- Inserção de professores
INSERT INTO Professor (Nome) VALUES
('Profa. a Definir'),
('Profa. Dra. Karen Espinosa'),
('Profa. Dra. Nanci de Oliveira'),
('Profa. Dra. Rita de Cássia von Randow'),
('Profa. Dra. Selma Candelária Genari'),
('Profa. Dra. Vivian Hyodo'),
('Profa. Esp. Joanize Aparecida dos Santos Mohallem Paiva'),
('Profa. Esp. Lucineide Nunes Pimenta'),
('Profa. Esp. Maria Lucia de Oliveira'),
('Profa. Esp. Mariana Timponi Rodrigues'),
('Profa. Ma. Adriana Antividad López Valverde'),
('Profa. Ma. Yara da Cruz Ferreira'),
('Profa. Msc. Jane Delane Verona'),
('Profa. Msc. Risleide Lucia dos Santos'),
('Profa. MSc. Fernanda da Silveira Bueno'),
('Prof. Dr. Arley Ferreira de Souza'),
('Prof. Dr. Daniel José de Andrade'),
('Prof. Dr. Érico Luciano Pagotto'),
('Prof. Dr. Fabrício Galende Marques de Carvalho'),
('Prof. Dr. Jorge Tadao Matsushima'),
('Prof. Dr. Nilton de Jesus'),
('Prof. Dr. Renato Mortin'),
('Prof. Dra. Sanzara Nhiaia J.C. Hassmann'),
('Prof. Esp. André Olímpio'),
('Prof. Esp. Henrique Duarte Borges Louro'),
('Prof. Esp. Marcelo Augusto Sudo'),
('Prof. Esp. Matheus de Oliveira Lorena'),
('Prof. Esp. Neymar Siqueira Dellareti'),
('Prof. M. Sc. Mario Sérgio Soléo Scalambrino'),
('Prof. M.Sc. Kenji Taniguchi'),
('Prof. M.Sc. Luiz Gustavo Galhardo Mendes'),
('Prof. MSc. Luiz Sérgio Gonçalves Aguiar'),
('Prof. Me. Adilson Rodolfo Neves'),
('Prof. Me. Antonio Egydio São Thiago Graça'),
('Prof. Me. Celso de Oliveira'),
('Prof. Me. Gerson Freitas Júnior'),
('Prof. Me. Paulo José Maria Filho'),
('Prof. Me. Rodrigo Monteiro de Barros Santana'),
('Prof. Me. Ronaldo Emerick Moreira'),
('Prof. Me. Wellington Rios'),
('Sem professor');

-- Inserção de disciplinas (DSM)
INSERT INTO Disciplina (Nome) VALUES
('Algoritmos e Lógica de Programação'),
('Análise Espacial e Modelagem em Terrenos'),
('Aprendizagem de Máquina'),
('Águas Subterrâneas'),
('Álgebra Linear'),
('Álgebra Linear e Geometria Analítica'),
('Avaliação de Impactos Ambientais e Análise de Risco'),
('Banco de Dados - Não Relacional'),
('Banco de Dados Geográficos'),
('Banco de Dados – Relacional'),
('Biologia'),
('Cálculo'),
('Cadastro Técnico Multifinalitário'),
('Cartografia'),
('Cartografia Aplicada'),
('Cartografia, Topografia e Batimetria'),
('Ciências Ambientais e das Águas'),
('Climatologia e Meteorologia'),
('Computação em Nuvem I'),
('Computação em Nuvem II'),
('Controle e Monitoramento da Poluição Atmosférica e Sonora'),
('Desenho Técnico'),
('Design Digital'),
('Desenvolvimento Web I'),
('Desenvolvimento Web II'),
('Desenvolvimento Web III'),
('Ecologia'),
('Ecotecnologia'),
('Educação Ambiental'),
('Engenharia de Software I'),
('Engenharia de Software II'),
('Energia Alternativas'),
('Estatística'),
('Estatística Aplicada'),
('Estrutura de Dados'),
('Experiência do Usuário'),
('Físico Química Aplicada à Gestão Ambiental'),
('Fotogrametria Analógica e Digital'),
('Fundamentos da Comunicação Empresarial'),
('Fundamentos da Redação Técnica'),
('Fundamentos de Física'),
('Fundamentos de Gestão Empresarial'),
('Fundamentos de Óptica'),
('Geociência Ambiental'),
('Geodesia'),
('Geoprocessamento'),
('Geoprocessamento Aplicado a Análises Ambientais'),
('Geoprocessamento Aplicado à Infraestrutura Urbana'),
('Geoprocessamento e Sistemas de Informação Geográfica'),
('Georreferenciamento de Imóveis Rurais'),
('Geomarketing'),
('Gestão Ágil de Projetos de Software'),
('Gestão da Qualidade'),
('Hidráulica Fluvial'),
('Hidrologia e Recursos Hídricos'),
('Inglês I'),
('Inglês II'),
('Inglês III'),
('Inglês IV'),
('Interação Humano Computador'),
('Integração e Análise de Dados Territoriais'),
('Integração e Entrega Contínua'),
('Introdução à Ciência da Geoinformação'),
('Internet das Coisas e Aplicações'),
('Laboratório de Des. Multiplataforma'),
('Laboratório de Desenvolvimento Web'),
('Lab. de Des. para Dispositivos Móveis'),
('Legislação Ambiental'),
('Limnologia'),
('Linguagem de Programação I'),
('Linguagem de Programação II'),
('Matemática Aplicada'),
('Matemática para Computação'),
('Metodologia da Pesquisa Científico-Tecnológica'),
('Microbiologia Ambiental'),
('Mineração de Dados'),
('Modelagem de Banco de Dados'),
('Modelagem de Banco de Dados Espacial'),
('Padrões de Distribuição de Informações em SIG'),
('Planejamento e Conservação Ambiental'),
('Planejamento e Drenagem Urbana'),
('Planejamento Integrado de Bacias Hidrográficas'),
('Posicionamento por Satélite'),
('Processamento de Linguagem Natural'),
('Processamento Digital de Imagens'),
('Programação para Dispositivos Móveis I'),
('Programação para Dispositivos Móveis II'),
('Projetos Ambientais I'),
('Projetos Ambientais II'),
('Projetos em Geoprocessamento'),
('Projetos em Geoprocessamento II'),
('Projeto de Sistemas de Informação Geográfica'),
('Qualidade e Testes de Software'),
('Química Geral'),
('Restauração Ecológica'),
('Revitalização de Rios e Recuperação de Áreas Degradadas'),
('Saneamento Ambiental I'),
('Saneamento Ambiental II'),
('Saúde e Segurança Ocupacional'),
('Segurança no Des. de Aplicações'),
('Sensoriamento Remoto e Clima'),
('Sensoriamento Remoto e Geoprocessamento'),
('Sensoriamento Remoto e Interpretação'),
('Sistemas de Gestão e Auditorias Ambientais'),
('Sistemas Operacionais e Redes de Comp.'),
('Sociologia Ambiental'),
('Tecnologias WEB Aplicadas a Sistemas de Informação Geográfica'),
('Técnicas de Programação I'),
('Técnicas de Programação II'),
('Topografia e Batimetria'),
('Turismo, Meio Ambiente e Recursos Hídricos'),
('Uso e Conservação dos Solos'),
('Ética Profissional e Patente');


-- Inserção de horários
INSERT INTO Horario (HoraInicial, HoraFinal) VALUES
('18:45:00', '19:35:00'),
('19:35:00', '20:25:00'),
('20:25:00', '21:25:00'),
('21:25:00', '22:15:00'),
('22:15:00', '23:05:00'),
('07:30:00', '08:20:00'),
('08:20:00', '09:10:00'),
('09:20:00', '10:10:00'),
('10:10:00', '11:00:00'),
('11:10:00', '12:00:00'),
('12:00:00', '12:50:00');

INSERT INTO Semana (Dia) VALUES
('Segunda-feira'),
('Terça-feira'),
('Quarta-feira'),
('Quinta-feira'),
('Sexta-feira'),
('Sábado'),
('Domingo');

  INSERT INTO Sala (Nome, Andar) VALUES
('Lab. de Química Ambiental', '0'),
('Lab. de Desenho e Topografia', '0'),
('Lab. de Microbiologia Ambiental', '0'),
('Lab. de Análises Ambientais', '0'),
('Lab. de Informática 101', '1'),
('Sala de Aula 102', '1'),
('Lab. de Informática 103', '1'),
('Sala de Aula 104', '1'),
('Lab. de Informática 105', '1'),
('Sala de Aula 106', '1'),
('Lab. de Informática 107', '1'),
('Lab. de Informática 108', '1'),
('Sala Maker 110', '1'),
('Sala de Áudio e Vídeo 201', '2'),
('Sala de Aula 202', '2'),
('Lab. Univesp 203', '2'),
('Sala de Aula 204', '2'),
('Lab. de Informática 205', '2'),
('Sala de Aula 206', '2'),
('Lab. de Informática 207', '2'),
('Lab. de Biologia 208', '2'),
('Lab. de Informática 209', '2'),
('Sala de Aula e Vídeo 210', '2');
